@startuml
!include ./src/Koos.Models/IEntity.puml
!include ./src/Koos.Models/Goal.puml
!include ./src/Koos.Services/ServiceBase.puml
!include ./src/Koos.Services/GoalServices.puml
!include ./src/Koos.Services/Extensions.puml
!include ./src/Koos.WebApp/Program.puml
!include ./src/Koos.WebApp/Startup.puml
!include ./src/Koos.Infrastructure/KoosDb.puml
!include ./src/Koos.WebApp/Code/KoosAuthProvider.puml
!include ./src/Koos.Models/obj/Debug/netstandard2.0/Koos.Models.AssemblyInfo.puml
!include ./src/Koos.Models/obj/Development/netstandard2.0/Koos.Models.AssemblyInfo.puml
!include ./src/Koos.Models/obj/Devlopment/netstandard2.0/Koos.Models.AssemblyInfo.puml
!include ./src/Koos.Models/obj/Release/netstandard2.0/Koos.Models.AssemblyInfo.puml
!include ./src/Koos.Services/obj/Debug/netstandard2.0/Koos.Services.AssemblyInfo.puml
!include ./src/Koos.Services/obj/Development/netstandard2.0/Koos.Services.AssemblyInfo.puml
!include ./src/Koos.Services/obj/Devlopment/netstandard2.0/Koos.Services.AssemblyInfo.puml
!include ./src/Koos.Services/obj/Release/netstandard2.0/Koos.Services.AssemblyInfo.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/Koos.WebApp.AssemblyInfo.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/Koos.WebApp.AssemblyInfo.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/Koos.WebApp.AssemblyInfo.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/Koos.WebApp.AssemblyInfo.puml
!include ./src/Koos.Infrastructure/obj/Debug/netstandard2.0/Koos.Infrastructure.AssemblyInfo.puml
!include ./src/Koos.Infrastructure/obj/Release/netstandard2.0/Koos.Infrastructure.AssemblyInfo.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/RazorDeclaration/App.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/RazorDeclaration/_Imports.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/Razor/App.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/Razor/_Imports.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/RazorDeclaration/App.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/RazorDeclaration/_Imports.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/Razor/App.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/Razor/_Imports.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/RazorDeclaration/App.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/RazorDeclaration/_Imports.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/Razor/App.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/Razor/_Imports.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/RazorDeclaration/App.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/RazorDeclaration/_Imports.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/Razor/App.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/Razor/_Imports.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/RazorDeclaration/Pages/Counter.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/RazorDeclaration/Pages/FetchData.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/RazorDeclaration/Pages/Index.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/RazorDeclaration/Pages/Goals.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/RazorDeclaration/Shared/MainLayout.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/RazorDeclaration/Shared/NavMenu.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/RazorDeclaration/Shared/SurveyPrompt.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/Razor/Pages/Counter.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/Razor/Pages/FetchData.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/Razor/Pages/Goals.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/Razor/Pages/Index.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/Razor/Shared/MainLayout.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/Razor/Shared/NavMenu.razor.g.puml
!include ./src/Koos.WebApp/obj/Debug/netstandard2.0/Razor/Shared/SurveyPrompt.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/RazorDeclaration/Pages/Counter.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/RazorDeclaration/Pages/FetchData.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/RazorDeclaration/Pages/Index.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/RazorDeclaration/Pages/Tasks.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/RazorDeclaration/Shared/MainLayout.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/RazorDeclaration/Shared/NavMenu.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/RazorDeclaration/Shared/SurveyPrompt.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/Razor/Pages/Counter.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/Razor/Pages/FetchData.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/Razor/Pages/Index.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/Razor/Pages/Tasks.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/Razor/Shared/MainLayout.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/Razor/Shared/NavMenu.razor.g.puml
!include ./src/Koos.WebApp/obj/Development/netstandard2.0/Razor/Shared/SurveyPrompt.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/RazorDeclaration/Pages/Counter.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/RazorDeclaration/Pages/FetchData.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/RazorDeclaration/Pages/Index.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/RazorDeclaration/Pages/Tasks.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/RazorDeclaration/Shared/MainLayout.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/RazorDeclaration/Shared/NavMenu.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/RazorDeclaration/Shared/SurveyPrompt.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/Razor/Pages/Counter.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/Razor/Pages/FetchData.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/Razor/Pages/Index.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/Razor/Pages/Tasks.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/Razor/Shared/MainLayout.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/Razor/Shared/NavMenu.razor.g.puml
!include ./src/Koos.WebApp/obj/Devlopment/netstandard2.0/Razor/Shared/SurveyPrompt.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/RazorDeclaration/Pages/Counter.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/RazorDeclaration/Pages/FetchData.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/RazorDeclaration/Pages/Index.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/RazorDeclaration/Pages/Goals.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/RazorDeclaration/Shared/MainLayout.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/RazorDeclaration/Shared/NavMenu.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/RazorDeclaration/Shared/SurveyPrompt.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/Razor/Pages/Counter.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/Razor/Pages/FetchData.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/Razor/Pages/Goals.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/Razor/Pages/Index.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/Razor/Shared/MainLayout.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/Razor/Shared/NavMenu.razor.g.puml
!include ./src/Koos.WebApp/obj/Release/netstandard2.0/Razor/Shared/SurveyPrompt.razor.g.puml
@enduml
